import type { Coupon, Offer, Store } from "./types";
import { AREA_STORES } from "./area-stores";

export const SEED_STORES: Store[] = AREA_STORES;

/** Canonical grocery intents the matcher understands well in demo mode */
const SEED_OFFERS_BASE: Offer[] = [
  // Milk
  {
    id: "gv-milk-gal",
    storeId: "green-valley",
    productId: "milk-gallon",
    name: "Valley Farms Whole Milk",
    brand: "Valley Farms",
    category: "dairy",
    sizeLabel: "1 gal",
    priceUsd: 4.29,
    unitAmount: 1,
    unitName: "gal",
    isLocal: true,
    localOrigin: "Tillamook, OR",
    onSale: false,
    couponIds: ["gv-dairy-50"],
  },
  {
    id: "hf-milk-gal",
    storeId: "harbor-fresh",
    productId: "milk-gallon",
    name: "Co-op Organic Whole Milk",
    brand: "Harbor Fresh",
    category: "dairy",
    sizeLabel: "1 gal",
    priceUsd: 5.49,
    unitAmount: 1,
    unitName: "gal",
    isLocal: true,
    localOrigin: "Willamette Valley, OR",
    onSale: true,
    salePriceUsd: 4.79,
    couponIds: [],
  },
  {
    id: "kr-milk-gal",
    storeId: "kroger-demo",
    productId: "milk-gallon",
    name: "Kroger Whole Milk",
    brand: "Kroger",
    category: "dairy",
    sizeLabel: "1 gal",
    priceUsd: 3.69,
    unitAmount: 1,
    unitName: "gal",
    isLocal: false,
    onSale: false,
    couponIds: ["kr-milk-clip"],
  },
  // Eggs
  {
    id: "gv-eggs-12",
    storeId: "green-valley",
    productId: "eggs-dozen",
    name: "Pasture Eggs Large Dozen",
    brand: "Sunrise Pastures",
    category: "dairy",
    sizeLabel: "12 ct",
    priceUsd: 5.99,
    unitAmount: 12,
    unitName: "ct",
    isLocal: true,
    localOrigin: "Canby, OR",
    onSale: true,
    salePriceUsd: 4.99,
    couponIds: [],
  },
  {
    id: "hf-eggs-12",
    storeId: "harbor-fresh",
    productId: "eggs-dozen",
    name: "Co-op Cage-Free Eggs",
    brand: "Harbor Fresh",
    category: "dairy",
    sizeLabel: "12 ct",
    priceUsd: 4.49,
    unitAmount: 12,
    unitName: "ct",
    isLocal: true,
    localOrigin: "Yamhill County, OR",
    onSale: false,
    couponIds: ["hf-local-10pct"],
  },
  {
    id: "kr-eggs-12",
    storeId: "kroger-demo",
    productId: "eggs-dozen",
    name: "Simple Truth Cage Free Eggs",
    brand: "Simple Truth",
    category: "dairy",
    sizeLabel: "12 ct",
    priceUsd: 3.99,
    unitAmount: 12,
    unitName: "ct",
    isLocal: false,
    onSale: true,
    salePriceUsd: 2.99,
    couponIds: [],
  },
  // Bread
  {
    id: "gv-bread",
    storeId: "green-valley",
    productId: "bread-wheat",
    name: "Baker Street Wheat Loaf",
    brand: "Baker Street",
    category: "bakery",
    sizeLabel: "24 oz",
    priceUsd: 4.49,
    unitAmount: 24,
    unitName: "oz",
    isLocal: true,
    localOrigin: "Portland, OR",
    onSale: false,
    couponIds: [],
  },
  {
    id: "hf-bread",
    storeId: "harbor-fresh",
    productId: "bread-wheat",
    name: "Co-op Multigrain Loaf",
    brand: "Harbor Bakery",
    category: "bakery",
    sizeLabel: "22 oz",
    priceUsd: 5.29,
    unitAmount: 22,
    unitName: "oz",
    isLocal: true,
    localOrigin: "Portland, OR",
    onSale: true,
    salePriceUsd: 3.99,
    couponIds: [],
  },
  {
    id: "kr-bread",
    storeId: "kroger-demo",
    productId: "bread-wheat",
    name: "Private Selection Wheat Bread",
    brand: "Private Selection",
    category: "bakery",
    sizeLabel: "24 oz",
    priceUsd: 3.29,
    unitAmount: 24,
    unitName: "oz",
    isLocal: false,
    onSale: false,
    couponIds: ["kr-bakery-1"],
  },
  {
    id: "gv-bread-ad",
    storeId: "green-valley",
    productId: "bread-wheat",
    name: "Sunrise Grain Honey Wheat",
    brand: "Sunrise Grain",
    category: "bakery",
    sizeLabel: "24 oz",
    priceUsd: 4.99,
    unitAmount: 24,
    unitName: "oz",
    isLocal: false,
    onSale: true,
    salePriceUsd: 3.79,
    couponIds: [],
    priceSource: "ad",
  },
  // Bananas
  {
    id: "gv-bananas",
    storeId: "green-valley",
    productId: "bananas",
    name: "Organic Bananas",
    category: "produce",
    sizeLabel: "1 lb",
    priceUsd: 0.89,
    unitAmount: 1,
    unitName: "lb",
    isLocal: false,
    onSale: false,
    couponIds: [],
  },
  {
    id: "hf-bananas",
    storeId: "harbor-fresh",
    productId: "bananas",
    name: "Fair Trade Bananas",
    category: "produce",
    sizeLabel: "1 lb",
    priceUsd: 0.99,
    unitAmount: 1,
    unitName: "lb",
    isLocal: false,
    onSale: true,
    salePriceUsd: 0.69,
    couponIds: [],
  },
  {
    id: "kr-bananas",
    storeId: "kroger-demo",
    productId: "bananas",
    name: "Bananas",
    category: "produce",
    sizeLabel: "1 lb",
    priceUsd: 0.59,
    unitAmount: 1,
    unitName: "lb",
    isLocal: false,
    onSale: false,
    couponIds: [],
  },
  // Chicken
  {
    id: "gv-chicken",
    storeId: "green-valley",
    productId: "chicken-breast",
    name: "Local Boneless Chicken Breast",
    brand: "Willamette Poultry",
    category: "meat",
    sizeLabel: "1 lb",
    priceUsd: 7.99,
    unitAmount: 1,
    unitName: "lb",
    isLocal: true,
    localOrigin: "Aurora, OR",
    onSale: true,
    salePriceUsd: 6.49,
    couponIds: [],
  },
  {
    id: "hf-chicken",
    storeId: "harbor-fresh",
    productId: "chicken-breast",
    name: "Organic Chicken Breast",
    brand: "Harbor Fresh",
    category: "meat",
    sizeLabel: "1 lb",
    priceUsd: 9.49,
    unitAmount: 1,
    unitName: "lb",
    isLocal: true,
    localOrigin: "Oregon",
    onSale: false,
    couponIds: ["hf-local-10pct"],
  },
  {
    id: "kr-chicken",
    storeId: "kroger-demo",
    productId: "chicken-breast",
    name: "Kroger Boneless Chicken Breast",
    brand: "Kroger",
    category: "meat",
    sizeLabel: "1 lb",
    priceUsd: 5.99,
    unitAmount: 1,
    unitName: "lb",
    isLocal: false,
    onSale: true,
    salePriceUsd: 4.49,
    couponIds: [],
  },
  // Rice
  {
    id: "gv-rice",
    storeId: "green-valley",
    productId: "rice-white",
    name: "Calrose White Rice",
    brand: "Valley Pantry",
    category: "pantry",
    sizeLabel: "5 lb",
    priceUsd: 6.99,
    unitAmount: 80,
    unitName: "oz",
    isLocal: false,
    onSale: false,
    couponIds: [],
  },
  {
    id: "hf-rice",
    storeId: "harbor-fresh",
    productId: "rice-white",
    name: "Organic Jasmine Rice",
    brand: "Harbor Fresh",
    category: "pantry",
    sizeLabel: "2 lb",
    priceUsd: 5.49,
    unitAmount: 32,
    unitName: "oz",
    isLocal: false,
    onSale: false,
    couponIds: [],
  },
  {
    id: "kr-rice",
    storeId: "kroger-demo",
    productId: "rice-white",
    name: "Kroger White Rice",
    brand: "Kroger",
    category: "pantry",
    sizeLabel: "5 lb",
    priceUsd: 4.29,
    unitAmount: 80,
    unitName: "oz",
    isLocal: false,
    onSale: true,
    salePriceUsd: 3.49,
    couponIds: [],
  },
  // Coffee
  {
    id: "gv-coffee",
    storeId: "green-valley",
    productId: "coffee-ground",
    name: "Stumptown Hair Bender Ground",
    brand: "Stumptown",
    category: "pantry",
    sizeLabel: "12 oz",
    priceUsd: 14.99,
    unitAmount: 12,
    unitName: "oz",
    isLocal: true,
    localOrigin: "Portland, OR",
    onSale: false,
    couponIds: ["gv-coffee-2"],
  },
  {
    id: "hf-coffee",
    storeId: "harbor-fresh",
    productId: "coffee-ground",
    name: "Co-op House Blend",
    brand: "Harbor Roasters",
    category: "pantry",
    sizeLabel: "12 oz",
    priceUsd: 11.99,
    unitAmount: 12,
    unitName: "oz",
    isLocal: true,
    localOrigin: "Portland, OR",
    onSale: true,
    salePriceUsd: 9.99,
    couponIds: ["hf-local-10pct"],
  },
  {
    id: "kr-coffee",
    storeId: "kroger-demo",
    productId: "coffee-ground",
    name: "Folgers Classic Roast",
    brand: "Folgers",
    category: "pantry",
    sizeLabel: "11.3 oz",
    priceUsd: 8.49,
    unitAmount: 11.3,
    unitName: "oz",
    isLocal: false,
    onSale: false,
    couponIds: [],
    priceSource: "ad",
  },
  // Olive oil
  {
    id: "gv-oil",
    storeId: "green-valley",
    productId: "olive-oil",
    name: "Oregon Olive Mill EVOO",
    brand: "Oregon Olive Mill",
    category: "pantry",
    sizeLabel: "500 ml",
    priceUsd: 18.99,
    unitAmount: 16.9,
    unitName: "oz",
    isLocal: true,
    localOrigin: "Dayton, OR",
    onSale: false,
    couponIds: [],
  },
  {
    id: "hf-oil",
    storeId: "harbor-fresh",
    productId: "olive-oil",
    name: "Co-op Extra Virgin Olive Oil",
    brand: "Harbor Fresh",
    category: "pantry",
    sizeLabel: "500 ml",
    priceUsd: 12.49,
    unitAmount: 16.9,
    unitName: "oz",
    isLocal: false,
    onSale: true,
    salePriceUsd: 9.99,
    couponIds: [],
  },
  {
    id: "kr-oil",
    storeId: "kroger-demo",
    productId: "olive-oil",
    name: "Private Selection EVOO",
    brand: "Private Selection",
    category: "pantry",
    sizeLabel: "500 ml",
    priceUsd: 8.99,
    unitAmount: 16.9,
    unitName: "oz",
    isLocal: false,
    onSale: false,
    couponIds: [],
  },
  // Extra intents so common list items aren't dropped from plans
  {
    id: "kr-yogurt",
    storeId: "kroger-demo",
    productId: "yogurt",
    name: "Kroger Plain Yogurt",
    brand: "Kroger",
    category: "dairy",
    sizeLabel: "32 oz",
    priceUsd: 3.49,
    unitAmount: 32,
    unitName: "oz",
    isLocal: false,
    onSale: false,
    couponIds: [],
  },
  {
    id: "kr-cheddar",
    storeId: "kroger-demo",
    productId: "cheddar-cheese",
    name: "Kroger Sharp Cheddar",
    brand: "Kroger",
    category: "dairy",
    sizeLabel: "8 oz",
    priceUsd: 3.29,
    unitAmount: 8,
    unitName: "oz",
    isLocal: false,
    onSale: true,
    salePriceUsd: 2.79,
    couponIds: [],
  },
  {
    id: "kr-tomatoes",
    storeId: "kroger-demo",
    productId: "tomatoes",
    name: "Roma Tomatoes",
    brand: "Produce",
    category: "produce",
    sizeLabel: "1 lb",
    priceUsd: 1.99,
    unitAmount: 1,
    unitName: "lb",
    isLocal: false,
    onSale: false,
    couponIds: [],
  },
  {
    id: "kr-oatmeal",
    storeId: "kroger-demo",
    productId: "oatmeal",
    name: "Kroger Old Fashioned Oats",
    brand: "Kroger",
    category: "pantry",
    sizeLabel: "42 oz",
    priceUsd: 4.49,
    unitAmount: 42,
    unitName: "oz",
    isLocal: false,
    onSale: false,
    couponIds: [],
  },
  {
    id: "kr-paper-towels",
    storeId: "kroger-demo",
    productId: "paper-towels",
    name: "Kroger Paper Towels",
    brand: "Kroger",
    category: "household",
    sizeLabel: "6 rolls",
    priceUsd: 8.99,
    unitAmount: 6,
    unitName: "ct",
    isLocal: false,
    onSale: false,
    couponIds: [],
  },
  {
    id: "kr-salsa",
    storeId: "kroger-demo",
    productId: "salsa",
    name: "Kroger Medium Salsa",
    brand: "Kroger",
    category: "pantry",
    sizeLabel: "16 oz",
    priceUsd: 2.49,
    unitAmount: 16,
    unitName: "oz",
    isLocal: false,
    onSale: false,
    couponIds: [],
  },
  {
    id: "kr-garlic",
    storeId: "kroger-demo",
    productId: "garlic",
    name: "Fresh Garlic",
    brand: "Produce",
    category: "produce",
    sizeLabel: "1 bulb",
    priceUsd: 0.69,
    unitAmount: 1,
    unitName: "each",
    isLocal: false,
    onSale: false,
    couponIds: [],
  },
  {
    id: "kr-sugar",
    storeId: "kroger-demo",
    productId: "sugar",
    name: "Kroger Granulated Sugar",
    brand: "Kroger",
    category: "pantry",
    sizeLabel: "4 lb",
    priceUsd: 3.99,
    unitAmount: 4,
    unitName: "lb",
    isLocal: false,
    onSale: false,
    couponIds: [],
  },
  {
    id: "kr-flour",
    storeId: "kroger-demo",
    productId: "flour",
    name: "Kroger All-Purpose Flour",
    brand: "Kroger",
    category: "pantry",
    sizeLabel: "5 lb",
    priceUsd: 2.99,
    unitAmount: 5,
    unitName: "lb",
    isLocal: false,
    onSale: false,
    couponIds: [],
  },
  {
    id: "kr-ground-beef",
    storeId: "kroger-demo",
    productId: "ground-beef",
    name: "Kroger Ground Beef 80/20",
    brand: "Kroger",
    category: "meat",
    sizeLabel: "1 lb",
    priceUsd: 5.49,
    unitAmount: 1,
    unitName: "lb",
    isLocal: false,
    onSale: true,
    salePriceUsd: 4.99,
    couponIds: [],
  },
  {
    id: "kr-black-beans",
    storeId: "kroger-demo",
    productId: "black-beans",
    name: "Kroger Black Beans",
    brand: "Kroger",
    category: "pantry",
    sizeLabel: "15 oz",
    priceUsd: 1.19,
    unitAmount: 15,
    unitName: "oz",
    isLocal: false,
    onSale: false,
    couponIds: [],
  },
];

const OFFER_TRAITS: Record<
  string,
  Partial<Pick<Offer, "isOrganic" | "isNonGmo" | "isKosher">>
> = {
  "hf-milk-gal": { isOrganic: true, isNonGmo: true, isKosher: true },
  "gv-milk-gal": { isNonGmo: true, isKosher: true },
  "kr-milk-gal": { isKosher: true },
  "gv-eggs-12": { isNonGmo: true },
  "hf-eggs-12": { isOrganic: true, isNonGmo: true, isKosher: true },
  "kr-eggs-12": { isNonGmo: true },
  "gv-bread": { isNonGmo: true },
  "hf-bread": { isOrganic: true, isNonGmo: true },
  "gv-bananas": { isOrganic: true, isNonGmo: true },
  "hf-bananas": { isOrganic: true, isNonGmo: true },
  "hf-chicken": { isOrganic: true, isNonGmo: true, isKosher: true },
  "gv-chicken": { isNonGmo: true, isKosher: true },
  "hf-rice": { isOrganic: true, isNonGmo: true, isKosher: true },
  "kr-rice": { isKosher: true },
  "gv-coffee": { isOrganic: true, isNonGmo: true },
  "hf-coffee": { isOrganic: true, isNonGmo: true },
  "gv-oil": { isOrganic: true, isNonGmo: true, isKosher: true },
  "hf-oil": { isOrganic: true, isNonGmo: true, isKosher: true },
  "kr-oil": { isKosher: true },
};

export const SEED_OFFERS: Offer[] = (() => {
  const coop = SEED_OFFERS_BASE.filter((o) => o.storeId !== "kroger-demo").map(
    applyTraits,
  );
  const templates = SEED_OFFERS_BASE.filter((o) => o.storeId === "kroger-demo");

  type CloneTarget = {
    storeId: string;
    prefix: string;
    /** Multiplier vs Kroger template shelf price */
    mul: number;
    brand?: string;
    rename?: (name: string) => string;
  };

  const targets: CloneTarget[] = [
    { storeId: "kroger-70100053", prefix: "fm53", mul: 1.0 },
    { storeId: "kroger-70100215", prefix: "fm215", mul: 1.01 },
    { storeId: "kroger-70100031", prefix: "fm31", mul: 1.02 },
    { storeId: "kroger-70100019", prefix: "fm19", mul: 0.99 },
    { storeId: "kroger-70100682", prefix: "fm682", mul: 1.015 },
    {
      storeId: "qfc-70500803",
      prefix: "qfc803",
      mul: 1.04,
      rename: (n) => n.replace(/^Kroger\b/i, "QFC").replace(/^Private Selection\b/i, "QFC"),
    },
    {
      storeId: "qfc-70500837",
      prefix: "qfc837",
      mul: 1.045,
      rename: (n) => n.replace(/^Kroger\b/i, "QFC").replace(/^Private Selection\b/i, "QFC"),
    },
    {
      storeId: "qfc-70500871",
      prefix: "qfc871",
      mul: 1.035,
      rename: (n) => n.replace(/^Kroger\b/i, "QFC").replace(/^Private Selection\b/i, "QFC"),
    },
    {
      storeId: "qfc-70500840",
      prefix: "qfc840",
      mul: 1.05,
      rename: (n) => n.replace(/^Kroger\b/i, "QFC").replace(/^Private Selection\b/i, "QFC"),
    },
    {
      storeId: "safeway-covington",
      prefix: "sw",
      mul: 1.08,
      brand: "Lucerne",
      rename: (n) =>
        n
          .replace(/^Kroger\b/i, "Lucerne")
          .replace(/^Simple Truth\b/i, "O Organics")
          .replace(/^Private Selection\b/i, "Signature SELECT"),
    },
    {
      storeId: "albertsons-kent",
      prefix: "ab",
      mul: 1.07,
      brand: "Signature",
      rename: (n) =>
        n
          .replace(/^Kroger\b/i, "Signature")
          .replace(/^Simple Truth\b/i, "O Organics")
          .replace(/^Private Selection\b/i, "Signature SELECT"),
    },
    {
      storeId: "costco-kent",
      prefix: "cs",
      mul: 0.88,
      brand: "Kirkland",
      rename: (n) =>
        n
          .replace(/^Kroger\b/i, "Kirkland Signature")
          .replace(/^Simple Truth\b/i, "Kirkland Signature")
          .replace(/^Private Selection\b/i, "Kirkland Signature"),
    },
  ];

  const cloned: Offer[] = [];
  for (const t of targets) {
    for (const o of templates) {
      const priceUsd = Math.round(o.priceUsd * t.mul * 100) / 100;
      const salePriceUsd =
        o.salePriceUsd != null
          ? Math.round(o.salePriceUsd * t.mul * 100) / 100
          : undefined;
      const name = t.rename ? t.rename(o.name) : o.name;
      cloned.push(
        applyTraits({
          ...o,
          id: `${t.prefix}-${o.id.replace(/^kr-/, "")}`,
          storeId: t.storeId,
          name,
          brand: t.brand ?? o.brand,
          priceUsd,
          salePriceUsd,
          couponIds: [],
          priceSource: "modeled",
        }),
      );
    }
  }

  return [...coop, ...cloned];
})();

function applyTraits(offer: Offer): Offer {
  const templateKey = offer.id.startsWith("kr-")
    ? offer.id
    : `kr-${offer.id.replace(/^[a-z]+\d*-/, "")}`;
  const traits = OFFER_TRAITS[offer.id] ?? OFFER_TRAITS[templateKey] ?? {};
  const organicFromName = /organic/i.test(offer.name);
  return {
    ...offer,
    isOrganic: traits.isOrganic ?? organicFromName,
    isNonGmo: traits.isNonGmo ?? organicFromName,
    isKosher: traits.isKosher ?? false,
  };
}

export const SEED_COUPONS: Coupon[] = [
  {
    id: "gv-dairy-50",
    storeId: "green-valley",
    title: "$0.50 off Valley Farms dairy",
    amountOffUsd: 0.5,
    productIds: ["milk-gallon"],
    expiresAt: "2026-12-31",
  },
  {
    id: "gv-coffee-2",
    storeId: "green-valley",
    title: "$2 off local coffee",
    amountOffUsd: 2,
    productIds: ["coffee-ground"],
    expiresAt: "2026-12-31",
  },
  {
    id: "hf-local-10pct",
    storeId: "harbor-fresh",
    title: "10% off locally sourced items",
    percentOff: 10,
    expiresAt: "2026-12-31",
  },
  {
    id: "kr-milk-clip",
    storeId: "kroger-demo",
    title: "$1 off gallon milk",
    amountOffUsd: 1,
    productIds: ["milk-gallon"],
    expiresAt: "2026-12-31",
  },
  {
    id: "kr-bakery-1",
    storeId: "kroger-demo",
    title: "$1 off bakery bread",
    amountOffUsd: 1,
    categories: ["bakery"],
    expiresAt: "2026-12-31",
  },
  {
    id: "sw-milk-clip",
    storeId: "safeway-covington",
    title: "$1 off gallon milk",
    amountOffUsd: 1,
    productIds: ["milk-gallon"],
    expiresAt: "2026-12-31",
  },
  {
    id: "ab-bakery-1",
    storeId: "albertsons-kent",
    title: "$1 off bakery bread",
    amountOffUsd: 1,
    categories: ["bakery"],
    expiresAt: "2026-12-31",
  },
];
