import type { Coupon, Offer, Store } from "./types";

export const SEED_STORES: Store[] = [
  {
    id: "green-valley",
    name: "Green Valley Market",
    address: "214 SE Hawthorne Blvd",
    zip: "97214",
    lat: 45.512,
    lng: -122.659,
    source: "seed",
  },
  {
    id: "harbor-fresh",
    name: "Harbor Fresh Co-op",
    address: "880 NW 23rd Ave",
    zip: "97210",
    lat: 45.529,
    lng: -122.698,
    source: "seed",
  },
  {
    id: "kroger-demo",
    name: "Kroger (demo mirror)",
    chain: "Kroger",
    address: "3300 SE Division St",
    zip: "97202",
    lat: 45.504,
    lng: -122.632,
    source: "seed",
  },
];

/** Canonical grocery intents the matcher understands well in demo mode */
export const SEED_OFFERS: Offer[] = [
  // Milk
  {
    id: "gv-milk-gal",
    storeId: "green-valley",
    productId: "milk-gallon",
    name: "Valley Farms Whole Milk",
    brand: "Valley Farms",
    category: "dairy",
    sizeLabel: "1 gal",
    priceUsd: 4.29,
    unitAmount: 1,
    unitName: "gal",
    isLocal: true,
    localOrigin: "Tillamook, OR",
    onSale: false,
    couponIds: ["gv-dairy-50"],
  },
  {
    id: "hf-milk-gal",
    storeId: "harbor-fresh",
    productId: "milk-gallon",
    name: "Co-op Organic Whole Milk",
    brand: "Harbor Fresh",
    category: "dairy",
    sizeLabel: "1 gal",
    priceUsd: 5.49,
    unitAmount: 1,
    unitName: "gal",
    isLocal: true,
    localOrigin: "Willamette Valley, OR",
    onSale: true,
    salePriceUsd: 4.79,
    couponIds: [],
  },
  {
    id: "kr-milk-gal",
    storeId: "kroger-demo",
    productId: "milk-gallon",
    name: "Kroger Whole Milk",
    brand: "Kroger",
    category: "dairy",
    sizeLabel: "1 gal",
    priceUsd: 3.69,
    unitAmount: 1,
    unitName: "gal",
    isLocal: false,
    onSale: false,
    couponIds: ["kr-milk-clip"],
  },
  // Eggs
  {
    id: "gv-eggs-12",
    storeId: "green-valley",
    productId: "eggs-dozen",
    name: "Pasture Eggs Large Dozen",
    brand: "Sunrise Pastures",
    category: "dairy",
    sizeLabel: "12 ct",
    priceUsd: 5.99,
    unitAmount: 12,
    unitName: "ct",
    isLocal: true,
    localOrigin: "Canby, OR",
    onSale: true,
    salePriceUsd: 4.99,
    couponIds: [],
  },
  {
    id: "hf-eggs-12",
    storeId: "harbor-fresh",
    productId: "eggs-dozen",
    name: "Co-op Cage-Free Eggs",
    brand: "Harbor Fresh",
    category: "dairy",
    sizeLabel: "12 ct",
    priceUsd: 4.49,
    unitAmount: 12,
    unitName: "ct",
    isLocal: true,
    localOrigin: "Yamhill County, OR",
    onSale: false,
    couponIds: ["hf-local-10pct"],
  },
  {
    id: "kr-eggs-12",
    storeId: "kroger-demo",
    productId: "eggs-dozen",
    name: "Simple Truth Cage Free Eggs",
    brand: "Simple Truth",
    category: "dairy",
    sizeLabel: "12 ct",
    priceUsd: 3.99,
    unitAmount: 12,
    unitName: "ct",
    isLocal: false,
    onSale: true,
    salePriceUsd: 2.99,
    couponIds: [],
  },
  // Bread
  {
    id: "gv-bread",
    storeId: "green-valley",
    productId: "bread-wheat",
    name: "Baker Street Wheat Loaf",
    brand: "Baker Street",
    category: "bakery",
    sizeLabel: "24 oz",
    priceUsd: 4.49,
    unitAmount: 24,
    unitName: "oz",
    isLocal: true,
    localOrigin: "Portland, OR",
    onSale: false,
    couponIds: [],
  },
  {
    id: "hf-bread",
    storeId: "harbor-fresh",
    productId: "bread-wheat",
    name: "Co-op Multigrain Loaf",
    brand: "Harbor Bakery",
    category: "bakery",
    sizeLabel: "22 oz",
    priceUsd: 5.29,
    unitAmount: 22,
    unitName: "oz",
    isLocal: true,
    localOrigin: "Portland, OR",
    onSale: true,
    salePriceUsd: 3.99,
    couponIds: [],
  },
  {
    id: "kr-bread",
    storeId: "kroger-demo",
    productId: "bread-wheat",
    name: "Private Selection Wheat Bread",
    brand: "Private Selection",
    category: "bakery",
    sizeLabel: "24 oz",
    priceUsd: 3.29,
    unitAmount: 24,
    unitName: "oz",
    isLocal: false,
    onSale: false,
    couponIds: ["kr-bakery-1"],
  },
  // Bananas
  {
    id: "gv-bananas",
    storeId: "green-valley",
    productId: "bananas",
    name: "Organic Bananas",
    category: "produce",
    sizeLabel: "1 lb",
    priceUsd: 0.89,
    unitAmount: 1,
    unitName: "lb",
    isLocal: false,
    onSale: false,
    couponIds: [],
  },
  {
    id: "hf-bananas",
    storeId: "harbor-fresh",
    productId: "bananas",
    name: "Fair Trade Bananas",
    category: "produce",
    sizeLabel: "1 lb",
    priceUsd: 0.99,
    unitAmount: 1,
    unitName: "lb",
    isLocal: false,
    onSale: true,
    salePriceUsd: 0.69,
    couponIds: [],
  },
  {
    id: "kr-bananas",
    storeId: "kroger-demo",
    productId: "bananas",
    name: "Bananas",
    category: "produce",
    sizeLabel: "1 lb",
    priceUsd: 0.59,
    unitAmount: 1,
    unitName: "lb",
    isLocal: false,
    onSale: false,
    couponIds: [],
  },
  // Chicken
  {
    id: "gv-chicken",
    storeId: "green-valley",
    productId: "chicken-breast",
    name: "Local Boneless Chicken Breast",
    brand: "Willamette Poultry",
    category: "meat",
    sizeLabel: "1 lb",
    priceUsd: 7.99,
    unitAmount: 1,
    unitName: "lb",
    isLocal: true,
    localOrigin: "Aurora, OR",
    onSale: true,
    salePriceUsd: 6.49,
    couponIds: [],
  },
  {
    id: "hf-chicken",
    storeId: "harbor-fresh",
    productId: "chicken-breast",
    name: "Organic Chicken Breast",
    brand: "Harbor Fresh",
    category: "meat",
    sizeLabel: "1 lb",
    priceUsd: 9.49,
    unitAmount: 1,
    unitName: "lb",
    isLocal: true,
    localOrigin: "Oregon",
    onSale: false,
    couponIds: ["hf-local-10pct"],
  },
  {
    id: "kr-chicken",
    storeId: "kroger-demo",
    productId: "chicken-breast",
    name: "Kroger Boneless Chicken Breast",
    brand: "Kroger",
    category: "meat",
    sizeLabel: "1 lb",
    priceUsd: 5.99,
    unitAmount: 1,
    unitName: "lb",
    isLocal: false,
    onSale: true,
    salePriceUsd: 4.49,
    couponIds: [],
  },
  // Rice
  {
    id: "gv-rice",
    storeId: "green-valley",
    productId: "rice-white",
    name: "Calrose White Rice",
    brand: "Valley Pantry",
    category: "pantry",
    sizeLabel: "5 lb",
    priceUsd: 6.99,
    unitAmount: 80,
    unitName: "oz",
    isLocal: false,
    onSale: false,
    couponIds: [],
  },
  {
    id: "hf-rice",
    storeId: "harbor-fresh",
    productId: "rice-white",
    name: "Organic Jasmine Rice",
    brand: "Harbor Fresh",
    category: "pantry",
    sizeLabel: "2 lb",
    priceUsd: 5.49,
    unitAmount: 32,
    unitName: "oz",
    isLocal: false,
    onSale: false,
    couponIds: [],
  },
  {
    id: "kr-rice",
    storeId: "kroger-demo",
    productId: "rice-white",
    name: "Kroger White Rice",
    brand: "Kroger",
    category: "pantry",
    sizeLabel: "5 lb",
    priceUsd: 4.29,
    unitAmount: 80,
    unitName: "oz",
    isLocal: false,
    onSale: true,
    salePriceUsd: 3.49,
    couponIds: [],
  },
  // Coffee
  {
    id: "gv-coffee",
    storeId: "green-valley",
    productId: "coffee-ground",
    name: "Stumptown Hair Bender Ground",
    brand: "Stumptown",
    category: "pantry",
    sizeLabel: "12 oz",
    priceUsd: 14.99,
    unitAmount: 12,
    unitName: "oz",
    isLocal: true,
    localOrigin: "Portland, OR",
    onSale: false,
    couponIds: ["gv-coffee-2"],
  },
  {
    id: "hf-coffee",
    storeId: "harbor-fresh",
    productId: "coffee-ground",
    name: "Co-op House Blend",
    brand: "Harbor Roasters",
    category: "pantry",
    sizeLabel: "12 oz",
    priceUsd: 11.99,
    unitAmount: 12,
    unitName: "oz",
    isLocal: true,
    localOrigin: "Portland, OR",
    onSale: true,
    salePriceUsd: 9.99,
    couponIds: ["hf-local-10pct"],
  },
  {
    id: "kr-coffee",
    storeId: "kroger-demo",
    productId: "coffee-ground",
    name: "Folgers Classic Roast",
    brand: "Folgers",
    category: "pantry",
    sizeLabel: "11.3 oz",
    priceUsd: 8.49,
    unitAmount: 11.3,
    unitName: "oz",
    isLocal: false,
    onSale: false,
    couponIds: [],
  },
  // Olive oil
  {
    id: "gv-oil",
    storeId: "green-valley",
    productId: "olive-oil",
    name: "Oregon Olive Mill EVOO",
    brand: "Oregon Olive Mill",
    category: "pantry",
    sizeLabel: "500 ml",
    priceUsd: 18.99,
    unitAmount: 16.9,
    unitName: "oz",
    isLocal: true,
    localOrigin: "Dayton, OR",
    onSale: false,
    couponIds: [],
  },
  {
    id: "hf-oil",
    storeId: "harbor-fresh",
    productId: "olive-oil",
    name: "Co-op Extra Virgin Olive Oil",
    brand: "Harbor Fresh",
    category: "pantry",
    sizeLabel: "500 ml",
    priceUsd: 12.49,
    unitAmount: 16.9,
    unitName: "oz",
    isLocal: false,
    onSale: true,
    salePriceUsd: 9.99,
    couponIds: [],
  },
  {
    id: "kr-oil",
    storeId: "kroger-demo",
    productId: "olive-oil",
    name: "Private Selection EVOO",
    brand: "Private Selection",
    category: "pantry",
    sizeLabel: "500 ml",
    priceUsd: 8.99,
    unitAmount: 16.9,
    unitName: "oz",
    isLocal: false,
    onSale: false,
    couponIds: [],
  },
];

export const SEED_COUPONS: Coupon[] = [
  {
    id: "gv-dairy-50",
    storeId: "green-valley",
    title: "$0.50 off Valley Farms dairy",
    amountOffUsd: 0.5,
    productIds: ["milk-gallon"],
    expiresAt: "2026-12-31",
  },
  {
    id: "gv-coffee-2",
    storeId: "green-valley",
    title: "$2 off local coffee",
    amountOffUsd: 2,
    productIds: ["coffee-ground"],
    expiresAt: "2026-12-31",
  },
  {
    id: "hf-local-10pct",
    storeId: "harbor-fresh",
    title: "10% off locally sourced items",
    percentOff: 10,
    expiresAt: "2026-12-31",
  },
  {
    id: "kr-milk-clip",
    storeId: "kroger-demo",
    title: "$1 off gallon milk digital coupon",
    amountOffUsd: 1,
    productIds: ["milk-gallon"],
    expiresAt: "2026-12-31",
  },
  {
    id: "kr-bakery-1",
    storeId: "kroger-demo",
    title: "$1 off bakery bread",
    amountOffUsd: 1,
    categories: ["bakery"],
    expiresAt: "2026-12-31",
  },
];
