# fly.toml app configuration file generated for grocer-lrrcsg on 2026-10-02T16:38:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'grocer-lrrcsg'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[env]
  APP_DB_PATH = '/app/data/app.sqlite'
  HOSTNAME = '0.0.0.0'
  NODE_ENV = 'production'
  PORT = '3000'
  PRICE_CACHE_PATH = '/app/data/prices.sqlite'

[[mounts]]
  source = 'grocer_data'
  destination = '/app/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
